### ISSUE TITLE
fatal: unable to access 'https://git.proxmox.com/git/perlmod.git/': The requested URL returned error: 500

### ISSUE THREAD

**Issue by breakingflower** [SaumonNet/proxmox-nixos#64]
I'm new to nixos. 
i have misterio77's config setup for flakes with home manager. 

Feel free to drop any best practices, i dont fully understand flakes .

I installed the source as follows:

```
{
  description = "NixOS config for framework";

  inputs = {
    # Nixpkgs
    nixpkgs.url = "github:nixos/nixpkgs/nixos-24.05";
    # You can access packages and modules from different nixpkgs revs
    # at the same time. Here's an working example:
    nixpkgs-unstable.url = "github:nixos/nixpkgs/nixos-unstable";

    # adding proxmox
    proxmox-nixos.url = "github:SaumonNet/proxmox-nixos";

    # Home manager
    home-manager.url = "github:nix-community/home-manager/release-24.05";
    home-manager.inputs.nixpkgs.follows = "nixpkgs";
  };

  outputs =
    {
      self,
      nixpkgs,
      home-manager,
      proxmox-nixos,
      ...
    }@inputs:
    let
      inherit (self) outputs;
      # Supported systems for your flake packages, shell, etc.
      systems = [
        "aarch64-linux"
        "i686-linux"
        "x86_64-linux"
        "aarch64-darwin"
        "x86_64-darwin"
      ];
      # This is a function that generates an attribute by calling a function you
      # pass to it, with each system as an argument
      forAllSystems = nixpkgs.lib.genAttrs systems;
    in
    {
      # Your custom packages
      # Accessible through 'nix build', 'nix shell', etc
      packages = forAllSystems (system: import ./pkgs nixpkgs.legacyPackages.${system});
      # Formatter for your nix files, available through 'nix fmt'
      # Other options beside 'alejandra' include 'nixpkgs-fmt'
      formatter = forAllSystems (system: nixpkgs.legacyPackages.${system}.alejandra);

      # Your custom packages and modifications, exported as overlays
      overlays = import ./overlays { inherit inputs; };
      # Reusable nixos modules you might want to export
      # These are usually stuff you would upstream into nixpkgs
      nixosModules = import ./modules/nixos;
      # Reusable home-manager modules you might want to export
      # These are usually stuff you would upstream into home-manager
      homeManagerModules = import ./modules/home-manager;
      # NixOS configuration entrypoint
      # Available through 'nixos-rebuild --flake .#your-hostname'
      nixosConfigurations = {
        # FIXME replace with your hostname
        nixos-framework = nixpkgs.lib.nixosSystem {
          specialArgs = {
            inherit inputs outputs;
          };
          # > Our main nixos configuration file <
          modules = [ 
            proxmox-nixos.nixosModules.proxmox-ve

            ({ pkgs, lib, ... }: {
              services.proxmox-ve.enable = true;
              nixpkgs.overlays = [
                proxmox-nixos.overlays.x86_64-linux
              ];      
            }) 
            ./nixos/configuration.nix

          ];
        };
      };

      # Standalone home-manager configuration entrypoint
      # Available through 'home-manager --flake .#your-username@your-hostname'
      homeConfigurations = {
        # FIXME replace with your username@hostname
        "<user>@nixos-framework" = home-manager.lib.homeManagerConfiguration {
          pkgs = nixpkgs.legacyPackages.x86_64-linux; # Home-manager requires 'pkgs' instance
          extraSpecialArgs = {
            inherit inputs outputs;
          };
          # > Our main home-manager configuration file <
          modules = [ ./home-manager/home.nix ];
        };
      };
    };
}
``` 
I get the following error: 
```
warning: could not read HEAD ref from repo at 'https://git.proxmox.com/git/perlmod.git', using 'master'
fatal: unable to access 'https://git.proxmox.com/git/perlmod.git/': The requested URL returned error: 500
```
The repo does not seem to exist. 

Any help appreciated.

**Comment by JulienMalka** [comment]
Hmm maybe proxmox discontinued this repository. We should fix that but what you can do in the meanwhile is use our cache.

**Comment by breakingflower** [comment]
can you please elaborate on how i would do that?

**Comment by lyc8503** [comment]
Came across the same problem with minimal setup:

```
proxmox-nixos.nixosModules.proxmox-ve

({ pkgs, lib, ... }: {
  services.proxmox-ve.enable = true;
  nixpkgs.overlays = [
    proxmox-nixos.overlays.${system}
  ];
})
```

Setting up a cache with below configuration doesn't seem to help too, still the same error.
```
nix = {
  settings = {
    extra-substituters = [
      "https://cache.saumon.network/proxmox-nixos"
    ];
    extra-trusted-public-keys = [
      "proxmox-nixos:nveXDuVVhFDRFx8Dn19f1WDEaNRJjPrF2CPD2D+m1ys="
    ];
  };
};
```

**Comment by Patricol** [comment]
Something's going on with their servers; but this might be a very easy fix. (@JulienMalka)

`git clone git://git.proxmox.com/git/perlmod.git` still works.
`git clone https://git.proxmox.com/git/*.git` didn't work with any repo of theirs that I tried; despite that URL format being listed as a fallback.

Their dev docs do [recommend](https://pve.proxmox.com/wiki/Developer_Documentation#Checking_out_a_git_repository) `git://` anyway; can we just switch the protocol on all the URLs?

**Comment by Patricol** [comment]
Also seconding that using the cache does not fix this for me.

**Comment by Patricol** [comment]
Yep; I'm able to build by just changing the protocols (and one hash) https://github.com/SaumonNet/proxmox-nixos/compare/main...Patricol:proxmox-nixos:main
